### PR TITLE
Docker image. Fixes #45

### LINKED ISSUE #45: Docker image
Could you publish a docker image for the tool? Then it is smooth to integrate in pipelines.

### PR DESCRIPTION
**Pull request by davidkarlsen**
Signed-off-by: David Karlsen <david@davidkarlsen.com>

---
This change is [Reviewable](https://reviewable.io/reviews/cyclonedx/cyclonedx-python/46)

### CODE REVIEW

**Comment by stevespringett** [comment]
Thanks for the PR @davidkarlsen. You've hit on something I've been thinking about recently - having a Docker container that encompasses all the runtime requirements for all CycloneDX implementations.

One thing that I want to avoid managing, if possible, are dedicated containers for each implementation. If there was an implementation that had:

- Python 3 (as this PR does)
- Node.js
- Ruby (for Gem and possibly Cocoapods)
- Rust
- Mono (.NET)
- Java
- PHP

Then it would be possible to add all implementations to a single container. This would be especially useful for polyglot projects. Whenever a new version of an implementation would be released, the container would be updated as well.

Thoughts?

**Comment by davidkarlsen** [comment]
I'd suggest the opposite - then you can run one focused container per language - and a lot smaller one. Even for polyglot-projects then could just switch between the different containers. Why?

* size of container -> speed
* usually a polyglot project will have independent builds per language anyway, due to build-tools, setup, doing stuff in parallel etc - just choose the appropriate container(s)
* container follows release-cycle
* easier to control environment independently per container

as an example I have a common dependency-track pipeline in our jenkins, as a shared-library snippet, which can detect language(s) and run the according tool for bom-generation

**Comment by davidkarlsen** [comment]
@stevespringett WDYT?

**Comment by stevespringett** [comment]
I've created a cyclonedx org on docker hub. There appears to be interest in having a .net container as well.

**Comment by davidkarlsen** [comment]
great - could you push out an image as well?
Seems to be no repos: https://hub.docker.com/u/cyclonedx
maybe master-branch and tags?

**Pull request merged**
