### PR TITLE
feat: environment licenses as proper SPDX

### LINKED ISSUE #459: feat: environment licenses as proper SPDX
Currently the licenses are [read from package metadata](https://github.com/CycloneDX/cyclonedx-python/blob/67f56e7bfa4fb9d50654ebd07ece1ad14377a355/cyclonedx_py/parser/environment.py#L73).
They also [come from trove classifiers](https://github.com/CycloneDX/cyclonedx-python/blob/67f56e7bfa4fb9d50654ebd07ece1ad14377a355/cyclonedx_py/parser/environment.py#L78).
Values are trove classifiers - read [list A](https://pypi.org/pypi?%3Aaction=list_classifiers) and [list B](https://pypi.org/classifiers/).
See also: PEP 639 <https://peps.python.org/pep-0639>
The current implementation results in named licenses like "MIT License" as this is the value from classifier `License :: OSI Approved :: MIT License`.

It would be great to have results as SPDX license IDs, instead of named licenses, if possible.
Therefore, some well-known classifiers might be mapped to SPDX names. The [library might already to the correct factory behavior](https://github.com/CycloneDX/cyclonedx-python-lib/blob/main/cyclonedx/factory/license.py#L28) that is needed to create SPDX instead of named.

All that is missing is a mapping from classifiers to SPDX ids.  
See latest _general_ list of SPDX ids: <https://spdx.org/licenses/>
See list of library-_supported_ SPDX ids: <https://github.com/CycloneDX/cyclonedx-python-lib/blob/main/cyclonedx/schema/spdx.schema.json>

:warning: ATTENTION:
some classifiers do not have a unique mapping to SPDX, the map 1:N.
For example trove `License :: Eiffel Forum License (EFL)` could be in SPDX either `EFL-1.0` or `EFL-2.0`. 
I would suggest skip unclear relations, and just map those that are 1:1.
See the thoughts in https://peps.python.org/pep-0639/#mapping-license-classifiers-to-spdx-identifiers

### PR DESCRIPTION
**Pull request by jkowalleck**
fixes #459

### CODE REVIEW

**Comment by andife** [comment]
I had just a quick looking at the result: https://github.com/andife/cyclonedx-python/actions/runs/6036254421
The result seems to be better.

But I've some question:

I do not know, but if we have a valid "id", do we also have to mention the "name"?

The explanation for "name": 
"If SPDX does not define the license used, this field may be used to provide the license name"
https://cyclonedx.org/docs/1.4/json/#components_items_licenses_items_license_name

grafik

According to the code, I thought

grafik
 could be mapped ?

**Comment by jkowalleck** [comment]
> I do not know, but if we have a valid "id", do we also have to mention the "name"?

impossible. according to CycloneDX specification it is EITHER `id` OR `name` required, not both, not none.


> According to the code, I thought [...]  could be mapped ?

how comes? 
https://github.com/CycloneDX/cyclonedx-python/blob/306e8a8d148bf2b58a8c7d2a4ec1bab02fb8b8cd/cyclonedx_py/_internal/license_trove_classifier.py#L82-L84

**Comment by andife** [comment]
> > I do not know, but if we have a valid "id", do we also have to mention the "name"?
> 
> impossible. according to CycloneDX specification it is EITHER `id` OR `name` required, not both, not none.

so for py-serializable we know the "Apache 2.0", it's an "id"... there should not be a "name" "Apache Software License"...? For this unique mapping in general we have already the solution => "Apache 2.0"

> 
> > According to the code, I thought [...]  could be mapped ?
> 
> how comes?
> 
> https://github.com/CycloneDX/cyclonedx-python/blob/306e8a8d148bf2b58a8c7d2a4ec1bab02fb8b8cd/cyclonedx_py/_internal/license_trove_classifier.py#L82-L84

you are right... maybe one has to ask Github per API...

**Comment by jkowalleck** [comment]
> so for py-serializable we know the "Apache 2.0", it's an "id"... there should not be a "name" "Apache Software License"...? For this unique mapping in general we have already the solution => "Apache 2.0"

where does this solution come from? 
please read https://peps.python.org/pep-0639/#mapping-license-classifiers-to-spdx-identifiers 


> maybe one has to ask Github per API...
Why? why would you ask githhub for an package that you have installed locally?

**Pull request merged**
