### PR TITLE
feat!: v4.0.0 

### PR DESCRIPTION
**Pull request by jkowalleck**
This is the main PR for all release `4.0.0` work. 
See progress: https://github.com/CycloneDX/cyclonedx-python/milestone/3

----

  ## Changelog

  See also the migration guide in the docs.

  - BC: Removed support for python < 3.8
  - BC: Removed deprecated shell script `cyclonedx-bom`; use `cyclonedx-py` instead
  - BC: Removed conda support. However, conda's Python environments are fully supported. See below.
  - BC: Removed public API. You may use the CLI instead, see chapter "usage" in the docs.
  - BC: Complete redesign of the CommandLineInterface(CLI):
    - Uses sub-commands for easy accessibility and divide in specific purposes and domains
    - Easy understandable flags, switches and options -- in accordance with the domains
    - Updated help pages, added usage examples 
  - Dozens of new features and fixes, such as:
    - _environment_ analyzer supports any Python (virtual) environment --
      including support for, but not limited to: _conda_, _Hatch_, _PDM_, _Pipenv_, _Poetry_, _venv_, _virtualenv_
    - _Poetry_ analyzer support groups, filtering, and such
    - _Pipenv_ analyzer support categories, filtering, and such
    - _requirements_ analyzer is feature complete and fixed
    - More details in the SBOM results (based on method)
    - PackageURLs may have more qualifiers (enabled per default, disable via `--short-PURLs`)
    - component properties according to [official taxonomy](https://github.com/CycloneDX/cyclonedx-property-taxonomy/blob/main/cdx/)
    - SBOM results may be validated (enabled per default, disable via `--no-validate`)
    - SBOM results may have dependency graph populated (if supported by method - applies to _environment_ and _Poetry_)
    - SBOM results may have root-component populated (if `pyproject` provided)
    - SBOM results are more `diff`-friendly and not just one long line of text
    - Fixed possible issues with input data encoding
    - May omit dev-dependencies or domain-specific groups/categories (if supported by method and issued by CLI switches)
    - Strip authentication secrets from (private) download/index URLs
    - Support CycloneDX 1.5 - which is the default now
  - Upgraded documentation, examples, ...
  - Complete rewrite from scratch
  - Dependencies were bumped, dropped, added, ...
  - QA and test suites were massively enhanced

## Documentation

see <https://cyclonedx-bom-tool.readthedocs.io/en/dev-4.0.0/>

## Release Candidate

Release candidates are available from PyPI:
```
python -m pip install cyclonedx-bom==4.0.0rc6   # install via pip
pipx install          cyclonedx-bom==4.0.0rc6   # install via pipx
poetry add            cyclonedx-bom==4.0.0rc6   # install via poetry
# ... you get the idea ...
```

Release candidates are available from dockerhub:
```
docker pull cyclonedx/cyclonedx-python:4.0.0-rc.6
```

----

  ### Includes/fixes/invalidates:

  - https://github.com/CycloneDX/cyclonedx-python/issues/40 
  - https://github.com/CycloneDX/cyclonedx-python/issues/289
  - https://github.com/CycloneDX/cyclonedx-python/issues/325
  - https://github.com/CycloneDX/cyclonedx-python/issues/349
  - https://github.com/CycloneDX/cyclonedx-python/issues/378 
  - https://github.com/CycloneDX/cyclonedx-python/issues/391 
  - https://github.com/CycloneDX/cyclonedx-python/issues/398 
  - https://github.com/CycloneDX/cyclonedx-python/issues/459 
  - https://github.com/CycloneDX/cyclonedx-python/issues/474
  - https://github.com/CycloneDX/cyclonedx-python/issues/475 
  - https://github.com/CycloneDX/cyclonedx-python/issues/488 
  - https://github.com/CycloneDX/cyclonedx-python/issues/491
  - https://github.com/CycloneDX/cyclonedx-python/issues/500 
  - https://github.com/CycloneDX/cyclonedx-python/issues/520
  - https://github.com/CycloneDX/cyclonedx-python/issues/522 
  - https://github.com/CycloneDX/cyclonedx-python/issues/523
  - https://github.com/CycloneDX/cyclonedx-python/issues/580
  - https://github.com/CycloneDX/cyclonedx-python/issues/586
  - https://github.com/CycloneDX/cyclonedx-python/issues/594 
  - https://github.com/CycloneDX/cyclonedx-python/issues/606 
  - https://github.com/CycloneDX/cyclonedx-python/issues/617 
  - https://github.com/CycloneDX/cyclonedx-python/issues/622 
  - https://github.com/CycloneDX/cyclonedx-python/issues/646
  - https://github.com/CycloneDX/cyclonedx-python/issues/651

----

coverage report here: https://github.com/CycloneDX/cyclonedx-python/pull/605#issuecomment-1890075359

### CODE REVIEW

**Comment by matejsp** [comment]
@jkowalleck I was testing latest cyclonedx-bom = "==4.0.0rc4" because I really like new features (like group support).

I noticed that before cyclonedx-py accepted Pipfile.lock as input, but now it wants a folder.
```
cyclonedx-py pipenv --output-format xml --schema-version 1.4 --categories dev --outfile generated_bom.xml tests/examples/pipenv/Pipfile.lock
CRITICAL | CDX > Could not open lock file: tests/examples/pipenv/Pipfile.lock/Pipfile.lock
cyclonedx-py pipenv --output-format xml --schema-version 1.4 --categories dev --outfile generated_bom.xml tests/examples/pipenv             
```

Old version expected to get Pipfile.lock as input:
```
cyclonedx-py --pip -i tests/examples/pipenv/
cyclonedx-py: error: argument -i/--in-file: can't open 'tests/examples/pipenv/': [Errno 21] Is a directory: 'tests/examples/pipenv/'
cyclonedx-py --pip -i tests/examples/pipenv/Pipfile.lock
```

**Comment by jkowalleck** [comment]
> I noticed that before cyclonedx-py accepted Pipfile.lock as input, but now it wants a folder.

That is right, the argument is a directory now. 
it is a directory, to allow analyzing not only the lockfile, but also the `Pipfile` and potentially other artifacts. 

@matejsp Do you see any problems with providing a directory? 

see the help page: 
```shellSession
$ cyclonedx-py pipenv --help
usage: cyclonedx-py pipenv [-h] [--categories <categories>] [-d] [--pypi-mirror <url>] [--pyproject <file>] [--mc-type <type>] [--short-PURLs] [-o <file>] [--sv <version>] [--of <format>]
                           [--output-reproducible] [--validate | --no-validate] [-v]
                           [<project-directory>]

Build an SBOM from Pipenv manifest.

The options and switches mimic the respective ones from Pipenv CLI.

positional arguments:
  <project-directory>   The project directory for Pipenv (default: current working directory) Unlike Pipenv tool, there is no search-up in this very tool. Please provide the actual
                        directory that contains `Pipfile` and `Pipfile.lock` file.

...
```

**Comment by matejsp** [comment]
Yes directory is fine too. I didn't read correctly that directory is now required because I was checking first the requirements parameters. But should actually check the difference for poetry and pipenv too.

Thanks for the explanation.

**Comment by JCHacking** [comment]
I am testing with poetry as I am interested in reporting only the production dependencies.

If I have a program A, that uses a library B that has a dependency C, I see that the dependency C does not appear in the report of my program A. Is this correct?

**Comment by jkowalleck** [comment]
@JCHacking 
re: https://github.com/CycloneDX/cyclonedx-python/pull/605#issuecomment-1888685033

It would be expected that the SBOM result included all transitive dependencies that were caused by the requested group(s).
Is this not the case? Could you share an example `pyproject.toml` and `poetry.lock` and tell how you called `cyclonedx-py poetry`?

**Comment by JCHacking** [comment]
Yes, it is uploaded in these 2 repositories:
https://github.com/JCHacking/program_a
https://github.com/JCHacking/library_b

If I execute this command with program_a:
`cyclonedx-py poetry --outfile dependencies_bom.xml --output-format XML`

I see that in the generated file is not the dependency of library_b, in this case aiohttp (This is the xml that I have generated in the repository so you can see it)

**Comment by jkowalleck** [comment]
@JCHacking your report will be handled here: https://github.com/CycloneDX/cyclonedx-python/issues/651

**Comment by JCHacking** [comment]
Hi @jkowalleck 

I have seen another strange thing, if I have an optional dependency as an extra, I understand that it should appear in the BOM since it is an optional production dependency.

I have opened an issue with an example #654

**Comment by JCHacking** [comment]
From the tests I have performed, in my use case everything works completely.

My use case is as follows
- Poetry
- Export dependencies from dependencies
- Sometime export also extra dependencies

**Comment by jkowalleck** [comment]
re https://github.com/CycloneDX/cyclonedx-python/pull/605#issuecomment-1891439130

@JCHacking thank you for your time and effort :-)

**Pull request merged**
