### PR TITLE
ci: release to GitHub registry

### LINKED ISSUE #695: chore: publish ContainerImage to alternative package
currently publishing to DockerHub.
why not publish to alternative package repository: GitHub Packageges - see <https://github.com/features/packages>

see https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

### PR DESCRIPTION
**Pull request by jxdv**
Closes #695.

`GHCR_USERNAME` and `GHCR_TOKEN` secret variables need to be set up.

Followed a similar template as `release-DockerHub` job, but I think both of these jobs could be simplified even more by using an already existing GitHub actions for releasing Docker images, such as: `docker/login-action`, `docker/build-push-action` etc. What do you think?

### CODE REVIEW

**Comment by jkowalleck** [comment]
I see your current solution and I wonder why we would build the container image twice, once for each registry.
I would envision to build the docker image once, tag it once, and then push it to each of the registries ...

**Comment by jxdv** [comment]
> I see your current solution and I wonder why we would build the container image twice, once for each registry. I would envision to build the docker image once, tag it once, and then push it to each of the registries ...

Potential solution:
1. Build the docker image in the first job
2. Turn the docker image into a tarball and save it as an artifact
3. load the tarball in the second job `docker load -i docker_image.tar`
4. push to registry

What do you think about this approach?

**Comment by jxdv** [comment]
> @jxdv , I wonder why all the effort. you could just modify the existing docker release workflow, right?
> 
> Is it not that the docker registry is determined by the tags? If so, just add a new tag, like here
> 

You are correct - my approach is redundant. I'll update this PR with the suggestions later today, or tomorrow.

**Comment by jxdv** [comment]
Changes in [newest commit](https://github.com/CycloneDX/cyclonedx-python/pull/721/commits/92bffd309a5a32de4e9dcdc957b48a7be407d21e):
- fixed typo
- renamed DOCKER_REPO to DOCKERHUB_REPO
- created tags for ghcr
- added login step for ghcr
- added steps to push new tags to ghcr

Please take a look now @jkowalleck

**Comment by jkowalleck** [comment]
Thanks a lot, @jxdv. 
I added some docs and tidy, updated the branch () and now all looks pretty golden.
The only thing that is left is, that you sign-off your commits, for the reasons described here: https://github.com/CycloneDX/cyclonedx-python/blob/main/CONTRIBUTING.md#sign-off-your-commits 

Here are instructions how to sign-off your commits: https://github.com/CycloneDX/cyclonedx-python/pull/721/checks?check_run_id=24056711557

**Review by jkowalleck — APPROVED** [review]

**Comment by jxdv** [comment]
@jkowalleck Had a little bit of issues with git while adding the DCO, but should be ready now.

**Pull request merged**
