### PR TITLE
Use minor version of base-image

### PR DESCRIPTION
**Pull request by davidkarlsen**

### CODE REVIEW

**Comment by davidkarlsen** [comment]
I see you have dependabot now - maybe use that on the docker image too? If so it can be the specific patch version tag.

**Comment by coderpatros** [comment]
@davidkarlsen thanks for the PR.

But I think Dependabot now supports Docker files. And I think it will be better to configure Dependabot to raise PRs for the referenced base image updates instead of referencing a minor version in the Docker file.

But I'll leave this open for now. The more deterministic behaviour is desirable. But if Dependabot doesn't really work for this it is probably a reasonable trade off for security.

**Comment by davidkarlsen** [comment]
https://github.com/CycloneDX/cyclonedx-python/pull/97 can obsolete this PR

**Comment by coderpatros** [comment]
Superseded by #97

**Pull request closed without merging**
