### PR TITLE
fix!: adjust python VCS related CycloneDX Properties Taxonomy names

### PR DESCRIPTION
**Pull request by jkowalleck**
in accordance with https://github.com/CycloneDX/cyclonedx-property-taxonomy/pull/96

### CODE REVIEW

**Comment by jkowalleck** [comment]
this might be considered a breaking-change, in case any of the changed enum values is used/applied when rendering CycloneDX.
need to check details

**Comment by madpah** [comment]
I see the quandry here - fix or breaking change - I'd err towards fix in this case (just).

**Comment by jkowalleck** [comment]
> I see the quandry here - fix or breaking change - I'd err towards fix in this case (just).

I'd consider it a breaking change, since the result/output changes in a way that ingesting pipelines and tools might break.

**Comment by madpah** [comment]
That is a fair point @jkowalleck alas we might end up with almost all changes becoming breaking changes...

**Comment by jkowalleck** [comment]
i might prepare a non-breaking patch, that introduces the fixed names in addition to the deprecated ones.
this way the fix is out and people can prepare for the breaking change.

**Comment by jkowalleck** [comment]
this PR needs to be reworked after #789 got merged

**Comment by jkowalleck** [comment]
superseded by #791

**Pull request closed without merging**
