### PR TITLE
Add a basic happy path test

### PR DESCRIPTION
**Pull request by coderpatros**
Have used tox+pytest to run tests against what actually gets packaged.

### CODE REVIEW

**Comment by coderpatros** [comment]
Ready for review @stevespringett

**Comment by coderpatros** [comment]
Finally got around to fixing the failing test @stevespringett

**Comment by coderpatros** [comment]
@stevespringett I was hoping to get some extra test data before pinging you again. But this is good to go as is.

**Comment by stevespringett** [comment]
Fantastic. Thank you.

**Pull request merged**
